### ISSUE TITLE
"marginal trees" -> "local trees"?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#10]
We settled after much debate on the term "local" trees in the ARG paper as "marginal" is confusing to those outside the immediate area.

There are 18 occurances of "marginal" and in my opinion a direct replacement with "local" for all of them is a straightforward improvement.

It's up to you @petrelharp, if you feel marginal is more in tune with the usage in the field I won't argue.

**Comment by petrelharp** [comment]
Sounds good! We should just say at first usage what that means (which we should have done for 'marginal' also).

**Comment by hfr1tz3** [comment]
I will make this change. The first reference of 'local trees' describes their usage as ``the genealogical trees that describe how each portion of the genome was inherited by the focal genomes.''
Let me know if we should change this to something else.

**Comment by hfr1tz3** [comment]
See [PR#21](https://github.com/petrelharp/num_edges/pull/21)
