### ISSUE TITLE
"An ARG" vs "the ARG"

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#11]
For various reasons I prefer to talk about  "an ARG" rather than "the ARG". For example, in the abstract:

> We show how these non-coalescing haplotypes (“unary regions”) may be inserted into **the** ancestral recombination graph (ARG), a compact but information-rich data structure describing the genealogical
relationships among recombinant sequences. The resulting ARGs...

Goes to

>  We show how these non-coalescing haplotypes (“unary regions”) may be inserted into ancestral recombination graphs (ARGs), a compact but information-rich data structure describing the genealogical relationships among recombinant sequences. The resulting ARGs...

I find it weird to refer to "the ARG" as both a data structure and specific instances of that data structure. For example, here

> the ARG shown in Figure 1 A&B, 

we're talking about a particular ARG (which is fine) whereas here

> We work with the succinct tree sequence representation of the ARG (henceforth, “tree sequence”),

we're talking about the abstract concept in the singular. (I would change this to "We work with the succinct tree sequence representation of ARGs  (henceforth, “tree sequence”)"

Talking about "the ARG" in the singular as a data structure or object reads to me in the same way as something like this:

> The Tree is a data structure representing genetic inheritance among nucleotides in a sequence.

This is another thing we spent ages debating for the ARG paper, wrote stuff about, and then cut.

**Comment by jeromekelleher** [comment]
This is a straightforward change that I'm happy to do btw, but I don't want to do it if others disagree (it does make me twitch though, so I really would like to make the change).

**Comment by petrelharp** [comment]
I like it!
