### ISSUE TITLE
Implementation of tscompare?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#13]
I got a surprise when I saw the similarity metric was implemented in tscompare! Although I don't see it? Where is the implementation? Should we change the wording of the preprint, or wait until there is a good implementation before posting?

**Comment by petrelharp** [comment]
https://github.com/tskit-dev/tscompare/pull/3

**Comment by petrelharp** [comment]
TODO: make sure we cite it correctly?
