### ISSUE TITLE
Drop "Inference methods" paragraph?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#17]
It's pretty weak, and we've already said we're just looking at tsinfer. This is leaving the reader at the end of the paper going "yes, but why on earth haven't they *tested* this, and given concrete definitive answers as to whether these methods do or don't benefit from haplotype extension".

I think we want to finish on a positive note here, talking about what has been done (extend edges! inventing new "metric"!) and how they can potentially be used in useful future work. At the moment, it's finishing up by specifically reminding the reader the most obvious missing bit.

**Comment by petrelharp** [comment]
Hm, good question. I was kinda trying to end on a positive note here, saying "look at all this more information! we'd like the field - ie other inference methods - to pay more attention to it". But, happy to remove it if you think that's better.

**Comment by nspope** [comment]
Wait-- is the suggestion here to drop the extend haplotypes stuff on tsinfer'd tree sequences, or to drop the "inference methods" paragraph which talks about other ARG inference methods like SINGER and Relate? I thought the latter -- the actual results on tsinfer'd tree sequences seem pretty important

**Comment by hfr1tz3** [comment]
Oh wait you're right @nspope. Ignore my last comment. I got my heading titles confused
